[package]
name = "voipglot-win"
version = "0.1.0"
edition = "2021"
authors = ["VoipGlot Team"]
description = "Real-time audio translation for Windows gaming and VOIP applications"

[dependencies]
# Audio processing
cpal = "0.16"
symphonia = { version = "0.6", features = ["all"] }
dasp = "0.12"

# Windows API bindings
windows = { version = "0.56", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_Media_Audio",
    "Win32_Media_MediaFoundation",
    "Win32_System_Threading",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
] }

# Async runtime
tokio = { version = "1.36", features = ["full"] }

# HTTP client for API calls
reqwest = { version = "0.12", features = ["json"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Configuration
config = "0.14"
toml = "0.8"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Utilities
clap = { version = "4.5", features = ["derive"] }
futures = "0.3"

# Additional dependencies
base64 = "0.22"
lazy_static = "1.4"

[target.'cfg(windows)'.dependencies]
# Windows-specific audio dependencies
windows = { version = "0.56", features = [
    "Win32_Media_Audio_Endpoints",
    "Win32_Media_Audio_CoreAudio",
    "Win32_System_Com_StructuredStorage",
] }

[dev-dependencies]
tokio-test = "0.4"

[[bin]]
name = "voipglot-win"
path = "src/main.rs" 