# VoipGlot Windows Audio Translation Configuration

[audio]
# Audio device settings
input_device = "Microphone Array (Realtek(R) Audio)"  # Set to specific device name or leave empty for default
output_device = "CABLE Input (VB-Audio Virtual Cable)"  # Set to specific device name or leave empty for default
sample_rate = 16000   # Sample rate in Hz (VOSK works best with 16kHz)
channels = 1          # Number of audio channels (1 = mono for VOSK)
buffer_size = 1024    # Audio buffer size in samples
latency_ms = 50       # Target latency in milliseconds

# VB Cable device configuration
vb_cable_device = "CABLE Input (VB-Audio Virtual Cable)"  # VB Cable input device name

[stt]
# VOSK Speech-to-Text settings
provider = "vosk"  # STT provider: vosk
model_path = "models/vosk-model-small-en-us-0.15"  # Path to VOSK model
sample_rate = 16000.0  # VOSK model sample rate
enable_partial_results = true  # Enable partial recognition results

[translation]
# CTranslate2 translation settings
provider = "ct2"  # Translation provider: ct2
model_path = "models/nllb-200-ct2"  # Path to CT2 model
source_language = "en"  # Source language code
target_language = "es"  # Target language code
num_threads = 4  # Number of translation threads
device = "cpu"  # Use CPU or GPU (cpu or cuda)
max_batch_size = 32  # Maximum batch size for translation
beam_size = 4  # Beam size for beam search

[tts]
# Custom Text-to-Speech settings
provider = "custom"  # TTS provider: custom
sample_rate = 22050  # TTS output sample rate
channels = 1  # TTS output channels (mono)
voice_speed = 1.0  # Voice speed multiplier
voice_pitch = 1.0  # Voice pitch multiplier

[processing]
# Audio processing settings
chunk_duration_ms = 1000  # Duration of audio chunks to process
silence_threshold = 0.01  # Threshold for silence detection
noise_reduction = true    # Enable noise reduction
echo_cancellation = true  # Enable echo cancellation

[logging]
# Logging configuration
level = "info"  # Log level (trace, debug, info, warn, error)
format = "simple"  # Log format (simple, json)
log_file = "voipglot.log"  # Log file path (optional) 