# VoipGlot Windows Audio Translation Configuration

[audio]
# Audio device settings
input_device = "Microphone Array (Realtek(R) Audio)"  # Set to specific device name or leave empty for default
output_device = ""  # Set to specific device name or leave empty for default
sample_rate = 16000   # Sample rate in Hz (VOSK works best with 16kHz)
channels = 1          # Number of audio channels (1 = mono for VOSK)
buffer_size = 1024    # Audio buffer size in samples (reduced for lower latency)
latency_ms = 50       # Target latency in milliseconds (reduced for better responsiveness)

# VB Cable device configuration
vb_cable_device = "CABLE Input (VB-Audio Virtual Cable)"  # VB Cable input device name

[stt]
# VOSK Speech-to-Text settings
provider = "vosk"  # STT provider: vosk
model_path = "models/vosk-model-small-en-us-0.15"  # Path to VOSK model
sample_rate = 16000.0  # VOSK model sample rate
enable_partial_results = true  # Enable partial recognition results

[translation]
# CTranslate2 translation settings
provider = "ct2"  # Translation provider: ct2
model_path = "models/nllb-200-ct2"  # Path to CT2 model
source_language = "en"  # Source language code
target_language = "es"  # Target language code
num_threads = 4  # Number of translation threads
device = "cpu"  # Use CPU or GPU (cpu or cuda)
max_batch_size = 32  # Maximum batch size for translation
beam_size = 4  # Beam size for beam search

[tts]
# Coqui TTS settings (Updated to match successful test implementation)
provider = "coqui"  # TTS provider: coqui
model_path = "tts_models/en/ljspeech/fast_pitch"  # Path to Coqui TTS model
sample_rate = 22050  # TTS output sample rate (matches test implementation)
channels = 1  # TTS output channels (mono)
voice_speed = 1.0  # Voice speed multiplier
voice_pitch = 1.0  # Voice pitch multiplier
enable_gpu = false  # Enable GPU acceleration (requires CUDA)

[processing]
# Audio processing settings
chunk_duration_ms = 300   # Duration of audio chunks to process (reduced for better responsiveness)
silence_threshold = 0.015  # Threshold for silence detection (slightly higher to reduce false triggers)
noise_reduction = false   # Disable noise reduction for better performance
echo_cancellation = false # Disable echo cancellation for better performance

[logging]
# Logging configuration
level = "info"  # Log level (trace, debug, info, warn, error)
format = "simple"  # Log format (simple, json)
log_file = "voipglot.log"  # Log file path (optional) 