[audio.input]
input_device = ""
sample_rate = 16000
channels = 1
buffer_size = 1024
latency_ms = 50
vb_cable_device = "CABLE Input (VB-Audio Virtual Cable)"

[audio.output]
output_device = ""
sample_rate = 48000
channels = 2
buffer_size = 2048
latency_ms = 100

[processing]
chunk_duration_ms = 100
silence_threshold = 0.01
noise_reduction = true
echo_cancellation = true
enable_feedback_prevention = true
tts_silence_buffer_ms = 50
tts_queue_size = 3

[stt]
provider = "vosk"
model_path = "../voipglot-core/models/vosk-model-small-en-us-0.15"
sample_rate = 16000.0
enable_partial_results = true

[translation]
provider = "ct2"
model_path = "../voipglot-core/models/nllb-200-ct2"
source_language = "eng_Latn"
target_language = "eng_Latn"
num_threads = 4
device = "cpu"
max_batch_size = 32
beam_size = 4

[tts]
provider = "coqui"
model_path = "../voipglot-core/models/tts_models/en/ljspeech/fast_pitch"
voice_speed = 1.0
voice_pitch = 1.0
enable_gpu = false
synthesis_timeout_secs = 5

[logging]
level = "info"
format = "simple"
log_file = "voipglot.log"
