[audio]
# Audio configuration
input_device = ""
output_device = ""
sample_rate = 16000
channels = 1
buffer_size = 1024
latency_ms = 50
vb_cable_device = "CABLE Input (VB-Audio Virtual Cable)"

[processing]
# Audio processing configuration
silence_threshold = 0.01
chunk_duration_ms = 100
noise_reduction = true
echo_cancellation = true

[stt]
# Speech-to-Text configuration (VOSK)
provider = "vosk"
# Models must be downloaded from https://alphacephei.com/vosk/models
# and then extracted to voipglot-win\models directory.
model_path = "models/vosk-model-small-en-in-0.4"
sample_rate = 16000.0
enable_partial_results = true

[translation]
# Translation configuration (CTranslate2)
provider = "ct2"
model_path = "models/nllb-200-ct2"
source_language = "eng_Latn"
target_language = "spa_Latn"
num_threads = 4
device = "cpu"
max_batch_size = 32
beam_size = 4

[tts]
# Text-to-Speech configuration (Coqui TTS)
provider = "coqui"
model_path = "tts_models/en/ljspeech/tacotron2-DDC"
sample_rate = 22050
channels = 1
voice_speed = 1.0
voice_pitch = 1.0
enable_gpu = false

[logging]
# Logging configuration
level = "info"
format = "simple"
log_file = "voipglot.log"
