# VoipGlot Windows Audio Translation Configuration

[audio]
# Audio device settings
input_device = "Microphone Array"  # Use your specific microphone device
output_device = "CABLE Input (VB-Audio Virtual Cable)"  # Explicitly use VB-CABLE for translated audio output
sample_rate = 48000   # Sample rate in Hz (matches VB-CABLE default)
channels = 2          # Number of audio channels (2 = stereo)
buffer_size = 1024    # Audio buffer size in samples
latency_ms = 50       # Target latency in milliseconds

[translation]
# Translation settings
source_language = "en"  # Source language code
target_language = "es"  # Target language code

[processing]
# Audio processing settings
chunk_duration_ms = 500   # Duration of audio chunks to process (reduced for faster processing)
silence_threshold = 0.0001  # Much lower threshold for better audio detection
noise_reduction = true    # Enable noise reduction
echo_cancellation = true  # Enable echo cancellation 