[build]
# Use the exact toolchain specified in rust-toolchain.toml
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-pc-windows-msvc]
# Windows-specific build settings
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=/SUBSYSTEM:CONSOLE"
]

# Force all C++ dependencies to use static runtime library
[env]
# Force static runtime library for all C++ dependencies
CXXFLAGS = "/MT"
CFLAGS = "/MT"
# Additional MSVC flags to ensure consistent runtime
CXXFLAGS_DEBUG = "/MTd"
CFLAGS_DEBUG = "/MTd"
CXXFLAGS_RELEASE = "/MT"
CFLAGS_RELEASE = "/MT"

[profile.release]
# Optimize for performance (slow build, fast runtime)
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.fast-release]
# Optimize for build speed (fast build, still good performance)
inherits = "release"
opt-level = 2
lto = false
codegen-units = 16
strip = false

[profile.dev]
# Faster debug builds
opt-level = 0
debug = true 