[build]
# Use the exact toolchain specified in rust-toolchain.toml
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-pc-windows-msvc]
# Windows-specific build settings
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=/SUBSYSTEM:CONSOLE",
    "-C", "link-arg=/ENTRY:mainCRTStartup"
]

[profile.release]
# Optimize for performance
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
# Faster debug builds
opt-level = 0
debug = true 